CREATE TABLE `enquiries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`subject` text NOT NULL,
	`message` text NOT NULL,
	`enquiry_type` text DEFAULT 'general' NOT NULL,
	`source` text DEFAULT 'website',
	`status` text DEFAULT 'new' NOT NULL,
	`priority` text DEFAULT 'medium',
	`assigned_to` text,
	`property_id` integer,
	`check_in_date` text,
	`check_out_date` text,
	`number_of_guests` integer,
	`occasion` text,
	`budget` real,
	`preferred_locations` text,
	`special_requests` text,
	`referral_source` text,
	`marketing_consent` integer DEFAULT false,
	`ip_address` text,
	`user_agent` text,
	`admin_notes` text,
	`internal_notes` text,
	`response_template` text,
	`responded_at` text,
	`responded_by` text,
	`resolved_at` text,
	`metadata` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`subscription_id` integer,
	`stripe_invoice_id` text,
	`stripe_payment_intent_id` text,
	`invoice_number` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`description` text,
	`amount_due` real NOT NULL,
	`amount_paid` real DEFAULT 0,
	`amount_remaining` real NOT NULL,
	`currency` text DEFAULT 'GBP' NOT NULL,
	`tax_amount` real DEFAULT 0,
	`subtotal` real NOT NULL,
	`total` real NOT NULL,
	`due_date` text,
	`paid_at` text,
	`invoice_date` text NOT NULL,
	`period_start` text,
	`period_end` text,
	`billing_reason` text,
	`customer_email` text NOT NULL,
	`customer_name` text NOT NULL,
	`invoice_pdf` text,
	`hosted_invoice_url` text,
	`metadata` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `invoices_stripe_invoice_id_unique` ON `invoices` (`stripe_invoice_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `invoices_invoice_number_unique` ON `invoices` (`invoice_number`);--> statement-breakpoint
CREATE TABLE `media` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`file_name` text NOT NULL,
	`file_url` text NOT NULL,
	`file_type` text NOT NULL,
	`mime_type` text NOT NULL,
	`file_size` integer NOT NULL,
	`width` integer,
	`height` integer,
	`duration` integer,
	`alt_text` text,
	`caption` text,
	`description` text,
	`title` text,
	`entity_type` text,
	`entity_id` text,
	`uploaded_by` text,
	`folder` text DEFAULT 'general',
	`tags` text,
	`is_public` integer DEFAULT true,
	`thumbnail_url` text,
	`metadata` text,
	`storage_provider` text DEFAULT 'supabase',
	`storage_key` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`uploaded_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `media_file_url_unique` ON `media` (`file_url`);--> statement-breakpoint
CREATE TABLE `subscriptions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`stripe_subscription_id` text,
	`stripe_price_id` text,
	`stripe_customer_id` text,
	`plan_name` text NOT NULL,
	`plan_type` text NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`current_period_start` text NOT NULL,
	`current_period_end` text NOT NULL,
	`cancel_at_period_end` integer DEFAULT false,
	`cancelled_at` text,
	`trial_start` text,
	`trial_end` text,
	`amount` real NOT NULL,
	`currency` text DEFAULT 'GBP' NOT NULL,
	`interval` text NOT NULL,
	`interval_count` integer DEFAULT 1,
	`metadata` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `subscriptions_stripe_subscription_id_unique` ON `subscriptions` (`stripe_subscription_id`);